### ISSUE TITLE
Projekt noch aktiv?

### ISSUE THREAD

**Issue by Tommekk** [bundestag/gesetze#59]
Hallo, ist das Projekt noch aktiv? Wenn nein, wäre ein Hinweis in der README sehr praktisch. Und gibt es Alternativen? Ich finde das Projekt sehr gut, aber der letzte Commit ist von 2013.

**Comment by ckujau** [comment]
Das scheint ein Duplikat von #55 zu sein.

**Comment by ulfgebhardt** [comment]
This project was created at `OKF` during their google-money-phase. Since then no substantial changes have been pushed.

There is a followup project https://github.com/bundestag/api.offenegesetze.de - you can ask them to push to this Repo or work with their code to implement that.

Since nobody worked on it since 2013 consider it your responsibility to make it happen. Ping me if you need any administrative stuff done.
